---
title: "Homework5"
author: "Kirti Agrawal"
date: "02/11/2021"
output:
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Answer1
```{r, error = TRUE}
library(neonDivData)
DT::datatable(head(neonDivData::data_plant, n = 100))
y = neonDivData::data_plant
library(dplyr, warn.conflicts = FALSE)
data_plant = select(y, siteID,
        starts_with("taxon"))
data_plant$x = data_plant$taxon_name
data_plant
library(tidyr)
j = data_plant %>% separate(c(x), c("genus", "Col2", "Col3"), " ")
j
data_plant <- j %>% select(-starts_with("Col"))
data_plant
print(data_plant[sample(nrow(data_plant), 100), ])
```


Answer2
```{r}
library(neonDivData)
y = neonDivData::data_plant
library(dplyr, warn.conflicts = FALSE)
data_plant = select(y, siteID,
               starts_with("taxon"), sample_area_m2,
       latitude, longitude, elevation)
data_plant$taxon_name2 = sub("(\\w+\\s+\\w+).*", "\\1", c(data_plant$taxon_name))
print(data_plant[sample(nrow(data_plant), 100), ])
```


Answer3
```{r}
n_1  <- data_plant %>% 
    group_by(siteID) %>% 
    summarise(richness_1m2 = n_distinct(sample_area_m2 == "1"))
n_1
n_10  <- data_plant %>% 
    group_by(siteID) %>% 
    summarise(richness_10m2 = n_distinct(sample_area_m2 %in% c("1", "10")))
n_10
n_100  <- data_plant %>% 
    group_by(siteID) %>% 
    summarise(richness_100m2 = n_distinct(sample_area_m2 %in% c("1", "10", "100")))
n_100
n_all = dplyr::left_join(n_1, n_10) %>% left_join(n_100)
n_all
```


Answer4
```{r}
library(tidyr)
n_all_long <- pivot_longer(n_all, cols=c(richness_1m2, richness_10m2, richness_100m2), names_to = "Spatial_scale", values_to = "Richness")
print(n_all_long)
```


Answer5
```{r, error = TRUE}
library(ggplot2)
p <- ggplot(n_all_long, aes(Spatial_scale, Richness))
p + geom_point(size = 4) + geom_line(aes(group = siteID))
```




**END**